services:
    web:
        build: .
        container_name: ${WEB_HOST}
        ports:
            - ${WEB_PORT}:8000
        profiles:
            - dont-start

    web-prod:
        extends:
            service: web
        depends_on:
            db-prod:
                condition: service_healthy
            cache-prod:
                condition: service_healthy
        command:
            python -O -m uvicorn
            --factory src.main:main
            --host 0.0.0.0
            --port 8000
            --workers ${WORKERS:-1}
            --log-level ${LOG_LEVEL:-trace}
        logging:
            driver: json-file
            options:
                max-size: ${LOG_SIZE:-10}m
                max-file: ${LOG_FILES:-3}
        profiles:
            - prod

    web-test:
        extends:
            service: web
        depends_on:
            db-dev-test:
                condition: service_healthy
            cache-dev-test:
                condition: service_healthy
        entrypoint: sh docker-entrypoint.sh
        command: pytest tests
        profiles:
            - test

    web-dev:
        extends:
            service: web
        depends_on:
            db-dev-test:
                condition: service_healthy
            cache-dev-test:
                condition: service_healthy
        command:
            uvicorn
            --factory src.main:main
            --host 0.0.0.0
            --port 8000
            --log-level ${LOG_LEVEL:-debug}
        develop:
            watch:
                - action: sync+restart
                  path: .
                  target: /app
                  ignore:
                      - pyproject.toml
                - action: rebuild
                  path: pyproject.toml
        volumes:
            - ./src/core/migrator/versions:/app/src/core/migrator/versions
        logging:
            driver: json-file
            options:
                max-size: ${LOG_SIZE:-3}m
                max-file: ${LOG_FILES:-1}
        profiles:
            - dev

    db:
        image: postgres:17.5
        container_name: ${DB_HOST}
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        healthcheck:
            test:
                pg_isready
                -U ${DB_USER}
                -d ${DB_NAME}
            interval: 10s
            timeout: 5s
            retries: 3
        profiles:
            - dont-start

    db-prod:
        extends:
            service: db
        volumes:
            - db-data:/var/lib/postgresql/data
        logging:
            driver: json-file
            options:
                max-size: ${LOG_SIZE:-3}m
                max-file: ${LOG_FILES:-1}
        profiles:
            - prod

    db-dev-test:
        extends:
            service: db
        ports:
            - "5432:5432"
        profiles:
            - dev
            - test

    cache:
        image: redis:8.0.3-bookworm
        container_name: ${CACHE_HOST}
        healthcheck:
            test:
                redis-cli
                -a ${CACHE_PASSWORD}
                ping
            interval: 10s
            timeout: 5s
            retries: 3
        command:
            redis-server
            --requirepass ${CACHE_PASSWORD}
            --maxmemory ${CACHE_SIZE:-256}mb
            --maxmemory-policy volatile-lfu
        profiles:
            - dont-start

    cache-prod:
        extends:
            service: cache
        volumes:
            - cache-data:/data
        logging:
            driver: json-file
            options:
                max-size: ${LOG_SIZE:-3}m
                max-file: ${LOG_FILES:-1}
        profiles:
            - prod

    cache-dev-test:
        extends:
            service: cache
        ports:
            - "6379:6379"
        profiles:
            - dev
            - test

volumes:
    db-data:
    cache-data:
