"""Initial revision

Revision ID: 05d7f15f0abd
Revises:
Create Date: 2025-07-17 11:29:21.583606

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "05d7f15f0abd"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
