"""Change float to decimal for accurancy

Revision ID: 0c93832207a3
Revises: 16966422abaf
Create Date: 2025-09-28 10:54:08.069343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import src.core.db.models


# revision identifiers, used by Alembic.
revision: str = '0c93832207a3'
down_revision: Union[str, Sequence[str], None] = '16966422abaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 'score',
               existing_type=sa.REAL(),
               type_=sa.Numeric(precision=8, scale=5),
               existing_comment='Average financial rating across all analytical reports.',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 'score',
               existing_type=sa.Numeric(precision=8, scale=5),
               type_=sa.REAL(),
               existing_comment='Average financial rating across all analytical reports.',
               existing_nullable=True)
    # ### end Alembic commands ###
