"""Apply naming convention

Revision ID: 810c78f8f000
Revises: 05d7f15f0abd
Create Date: 2025-07-19 11:32:09.788661

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "810c78f8f000"
down_revision: str | Sequence[str] | None = "05d7f15f0abd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
