"""Correct 'ratios' table fk ref from 'companies' to 'analytics'

Revision ID: cee77640d44a
Revises: 58f3e0bd6fa6
Create Date: 2025-09-26 10:44:40.332663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import src.core.db.models


# revision identifiers, used by Alembic.
revision: str = 'cee77640d44a'
down_revision: Union[str, Sequence[str], None] = '58f3e0bd6fa6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 'score',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2, asdecimal=True),
               existing_comment='Average financial rating across all analytical reports.',
               existing_nullable=True)
    op.drop_constraint(op.f('fk_ratios_analytics_id_companies'), 'ratios', type_='foreignkey')
    op.create_foreign_key(op.f('fk_ratios_analytics_id_analytics'), 'ratios', 'analytics', ['analytics_id'], ['id'], onupdate='RESTRICT', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_ratios_analytics_id_analytics'), 'ratios', type_='foreignkey')
    op.create_foreign_key(op.f('fk_ratios_analytics_id_companies'), 'ratios', 'companies', ['analytics_id'], ['id'], onupdate='RESTRICT', ondelete='CASCADE')
    op.alter_column('companies', 'score',
               existing_type=sa.Float(precision=2, asdecimal=True),
               type_=sa.REAL(),
               existing_comment='Average financial rating across all analytical reports.',
               existing_nullable=True)
    # ### end Alembic commands ###
